site_name: TH BioData Consulting
site_description: Transforming biological complexity into clear, data-driven insight.
site_url: https://thbiodata.github.io
theme:
  name: material
  logo: assets/logo.png        # (opcional: si sub√≠s el logo)
  favicon: assets/favicon.png  # (opcional)
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: blue        # barra superior azul
      accent: light blue   # acentos
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - codehilite
nav:
  - Home: index.md
  - Services: services.md
  - Projects: projects.md
  - Contact: contact.md
extra_css:
  - styles/extra.css

